In [3]:
import numpy as np
import pandas as pd

import yfinance as yf
eps = 1e-8

In [4]:
data = yf.download(["AMZN", "AAPL"], start="1995-01-01", end="2018-01-01")
data.head()

[*********************100%***********************]  2 of 2 completed

Price      Adj Close          Close           High            Low       \
Ticker          AAPL AMZN      AAPL AMZN      AAPL AMZN      AAPL AMZN
Date
1995-01-03  0.285766  NaN  0.342634  NaN  0.347098  NaN  0.338170  NaN
1995-01-04  0.293213  NaN  0.351563  NaN  0.353795  NaN  0.344866  NaN
1995-01-05  0.289489  NaN  0.347098  NaN  0.351563  NaN  0.345982  NaN
1995-01-06  0.312760  NaN  0.375000  NaN  0.385045  NaN  0.367188  NaN
1995-01-09  0.306826  NaN  0.367885  NaN  0.373884  NaN  0.366071  NaN

Price           Open           Volume
Ticker          AAPL AMZN        AAPL AMZN
Date
1995-01-03  0.347098  NaN   103868800  NaN
1995-01-04  0.344866  NaN   158681600  NaN
1995-01-05  0.350446  NaN    73640000  NaN
1995-01-06  0.371652  NaN  1076622400  NaN
1995-01-09  0.371652  NaN   274086400  NaN

In [5]:
data.fillna(eps, inplace=True)
data

Price       Adj Close                    Close                     High  \
Ticker           AAPL          AMZN       AAPL          AMZN       AAPL
Date
1995-01-03   0.285766  1.000000e-08   0.342634  1.000000e-08   0.347098
1995-01-04   0.293213  1.000000e-08   0.351563  1.000000e-08   0.353795
1995-01-05   0.289489  1.000000e-08   0.347098  1.000000e-08   0.351563
1995-01-06   0.312760  1.000000e-08   0.375000  1.000000e-08   0.385045
1995-01-09   0.306826  1.000000e-08   0.367885  1.000000e-08   0.373884
...               ...           ...        ...           ...        ...
2017-12-22  41.171288  5.841800e+01  43.752499  5.841800e+01  43.855000
2017-12-26  40.126774  5.883800e+01  42.642502  5.883800e+01  42.867500
2017-12-27  40.133831  5.911300e+01  42.650002  5.911300e+01  42.695000
2017-12-28  40.246754  5.930500e+01  42.770000  5.930500e+01  42.962502
2017-12-29  39.811535  5.847350e+01  42.307499  5.847350e+01  42.647499

Price                           Low                     Open                \
Ticker              AMZN       AAPL          AMZN       AAPL          AMZN
Date
1995-01-03  1.000000e-08   0.338170  1.000000e-08   0.347098  1.000000e-08
1995-01-04  1.000000e-08   0.344866  1.000000e-08   0.344866  1.000000e-08
1995-01-05  1.000000e-08   0.345982  1.000000e-08   0.350446  1.000000e-08
1995-01-06  1.000000e-08   0.367188  1.000000e-08   0.371652  1.000000e-08
1995-01-09  1.000000e-08   0.366071  1.000000e-08   0.371652  1.000000e-08
...                  ...        ...           ...        ...           ...
2017-12-22  5.873100e+01  43.625000  5.839150e+01  43.669998  5.860400e+01
2017-12-26  5.891600e+01  42.419998  5.802750e+01  42.700001  5.841800e+01
2017-12-27  5.936450e+01  42.427502  5.878050e+01  42.525002  5.899550e+01
2017-12-28  5.950500e+01  42.619999  5.921900e+01  42.750000  5.945000e+01
2017-12-29  5.920000e+01  42.305000  5.837500e+01  42.630001  5.911750e+01

Price           Volume
Ticker            AAPL          AMZN
Date
1995-01-03   103868800  1.000000e-08
1995-01-04   158681600  1.000000e-08
1995-01-05    73640000  1.000000e-08
1995-01-06  1076622400  1.000000e-08
1995-01-09   274086400  1.000000e-08
...                ...           ...
2017-12-22    65397600  3.170200e+07
2017-12-26   132742000  4.010400e+07
2017-12-27    85992800  3.734400e+07
2017-12-28    65920800  3.683400e+07
2017-12-29   103999600  5.376800e+07

[5791 rows x 12 columns]

In [6]:
stocks = data.columns.get_level_values(1).unique()
for stock in stocks:
    data["1D Return", stock] = data["Adj Close", stock].pct_change()
    data["5D Return", stock] = data["Close", stock].pct_change(5)
    data["20D Return", stock] = data["Close", stock].pct_change(20)
    data["80D Return", stock] = data["Close", stock].pct_change(80)
    data["120D Return", stock] = data["Close", stock].pct_change(120)
    data["160D Return", stock] = data["Close", stock].pct_change(160)
    data["200D Return", stock] = data["Close", stock].pct_change(200)
    data["20D EMA", stock] = data["Close", stock].ewm(span=20, adjust=False).mean()
    data["80D EMA", stock] = data["Close", stock].ewm(span=80, adjust=False).mean()
    data["120D EMA", stock] = data["Close", stock].ewm(span=120, adjust=False).mean()
    data["160D EMA", stock] = data["Close", stock].ewm(span=160, adjust=False).mean()
    data["200D EMA", stock] = data["Close", stock].ewm(span=200, adjust=False).mean()

In [7]:
targs = data.pop("1D Return")
for i in targs:
    data.insert(0, ("1D Return", i), targs[i])
data

Price      1D Return            Adj Close                    Close  \
Ticker          AMZN      AAPL       AAPL          AMZN       AAPL
Date
1995-01-03       NaN       NaN   0.285766  1.000000e-08   0.342634
1995-01-04  0.000000  0.026060   0.293213  1.000000e-08   0.351563
1995-01-05  0.000000 -0.012701   0.289489  1.000000e-08   0.347098
1995-01-06  0.000000  0.080387   0.312760  1.000000e-08   0.375000
1995-01-09  0.000000 -0.018973   0.306826  1.000000e-08   0.367885
...              ...       ...        ...           ...        ...
2017-12-22 -0.005448  0.000000  41.171288  5.841800e+01  43.752499
2017-12-26  0.007190 -0.025370  40.126774  5.883800e+01  42.642502
2017-12-27  0.004674  0.000176  40.133831  5.911300e+01  42.650002
2017-12-28  0.003248  0.002814  40.246754  5.930500e+01  42.770000
2017-12-29 -0.014021 -0.010814  39.811535  5.847350e+01  42.307499

Price                          High                      Low                \
Ticker              AMZN       AAPL          AMZN       AAPL          AMZN
Date
1995-01-03  1.000000e-08   0.347098  1.000000e-08   0.338170  1.000000e-08
1995-01-04  1.000000e-08   0.353795  1.000000e-08   0.344866  1.000000e-08
1995-01-05  1.000000e-08   0.351563  1.000000e-08   0.345982  1.000000e-08
1995-01-06  1.000000e-08   0.385045  1.000000e-08   0.367188  1.000000e-08
1995-01-09  1.000000e-08   0.373884  1.000000e-08   0.366071  1.000000e-08
...                  ...        ...           ...        ...           ...
2017-12-22  5.841800e+01  43.855000  5.873100e+01  43.625000  5.839150e+01
2017-12-26  5.883800e+01  42.867500  5.891600e+01  42.419998  5.802750e+01
2017-12-27  5.911300e+01  42.695000  5.936450e+01  42.427502  5.878050e+01
2017-12-28  5.930500e+01  42.962502  5.950500e+01  42.619999  5.921900e+01
2017-12-29  5.847350e+01  42.647499  5.920000e+01  42.305000  5.837500e+01

Price       ... 20D Return 80D Return 120D Return 160D Return 200D Return  \
Ticker      ...       AMZN       AMZN        AMZN        AMZN        AMZN
Date        ...
1995-01-03  ...        NaN        NaN         NaN         NaN         NaN
1995-01-04  ...        NaN        NaN         NaN         NaN         NaN
1995-01-05  ...        NaN        NaN         NaN         NaN         NaN
1995-01-06  ...        NaN        NaN         NaN         NaN         NaN
1995-01-09  ...        NaN        NaN         NaN         NaN         NaN
...         ...        ...        ...         ...         ...         ...
2017-12-22  ...  -0.014874   0.207495    0.202759    0.231097    0.370575
2017-12-26  ...  -0.015947   0.200041    0.219264    0.235029    0.376988
2017-12-27  ...  -0.009501   0.208546    0.207916    0.245861    0.386766
2017-12-28  ...   0.021382   0.228775    0.190302    0.251662    0.390553
2017-12-29  ...  -0.006187   0.208380    0.176375    0.216487    0.370333

Price            20D EMA       80D EMA      120D EMA      160D EMA  \
Ticker              AMZN          AMZN          AMZN          AMZN
Date
1995-01-03  1.000000e-08  1.000000e-08  1.000000e-08  1.000000e-08
1995-01-04  1.000000e-08  1.000000e-08  1.000000e-08  1.000000e-08
1995-01-05  1.000000e-08  1.000000e-08  1.000000e-08  1.000000e-08
1995-01-06  1.000000e-08  1.000000e-08  1.000000e-08  1.000000e-08
1995-01-09  1.000000e-08  1.000000e-08  1.000000e-08  1.000000e-08
...                  ...           ...           ...           ...
2017-12-22  5.820223e+01  5.440546e+01  5.274148e+01  5.136167e+01
2017-12-26  5.826278e+01  5.451491e+01  5.284225e+01  5.145454e+01
2017-12-27  5.834375e+01  5.462844e+01  5.294590e+01  5.154968e+01
2017-12-28  5.843530e+01  5.474391e+01  5.305101e+01  5.164602e+01
2017-12-29  5.843894e+01  5.483600e+01  5.314064e+01  5.173083e+01

Price           200D EMA
Ticker              AMZN
Date
1995-01-03  1.000000e-08
1995-01-04  1.000000e-08
1995-01-05  1.000000e-08
1995-01-06  1.000000e-08
1995-01-09  1.000000e-08
...                  ...
2017-12-22  5.011973e+01
2017-12-26  5.020648e+01
2017-12-27  5.029510e+01
2017-12-28  5.038475e+01
2017-12-29  5.046523e+01

[5791 rows x 36 columns]