In [1]:
import pandas as pd
import os

chosen_year = "2023"


data = pd.read_pickle(f'./snp/{chosen_year}.pkl')
data

Price                             Adj Close       Close        High  \
Date                      Ticker
2023-01-03 00:00:00+00:00 A             NaN  150.039993  153.130005
                          AAPL          NaN  125.070000  130.899994
                          ABBV          NaN  162.380005  163.020004
                          ABNB          NaN   84.900002   88.139999
                          ABT           NaN  109.580002  111.330002
...                                     ...         ...         ...
2023-12-29 00:00:00+00:00 XYL           NaN  114.360001  114.680000
                          YUM           NaN  130.660004  131.250000
                          ZBH           NaN  121.699997  122.400002
                          ZBRA          NaN  273.329987  276.309998
                          ZTS           NaN  197.369995  198.009995

Price                                    Low        Open       Volume
Date                      Ticker
2023-01-03 00:00:00+00:00 A       148.470001  151.960007    1414300.0
                          AAPL    124.169998  130.279999  112117500.0
                          ABBV    160.809998  162.039993    4937500.0
                          ABNB     84.300003   87.385002    3901200.0
                          ABT     108.750000  110.510002    4171900.0
...                                      ...         ...          ...
2023-12-29 00:00:00+00:00 XYL     113.930000  114.089996     698900.0
                          YUM     130.210007  130.410004    1196800.0
                          ZBH     121.239998  121.459999     849600.0
                          ZBRA    272.769989  274.730011     251300.0
                          ZTS     196.250000  196.679993    1007200.0

[123977 rows x 6 columns]

In [2]:
data["Day Percent Change"] = (data["Close"] - data["Open"]) / data["Open"]

In [3]:
# Calculate the change between each day's close and the previous day's close for each ticker
data['Previous Close'] = data.groupby(level='Ticker')['Close'].shift(1)
data['Percent Change'] = (data['Close'] - data['Previous Close']) / data['Previous Close']
data

Price                             Adj Close       Close        High  \
Date                      Ticker
2023-01-03 00:00:00+00:00 A             NaN  150.039993  153.130005
                          AAPL          NaN  125.070000  130.899994
                          ABBV          NaN  162.380005  163.020004
                          ABNB          NaN   84.900002   88.139999
                          ABT           NaN  109.580002  111.330002
...                                     ...         ...         ...
2023-12-29 00:00:00+00:00 XYL           NaN  114.360001  114.680000
                          YUM           NaN  130.660004  131.250000
                          ZBH           NaN  121.699997  122.400002
                          ZBRA          NaN  273.329987  276.309998
                          ZTS           NaN  197.369995  198.009995

Price                                    Low        Open       Volume  \
Date                      Ticker
2023-01-03 00:00:00+00:00 A       148.470001  151.960007    1414300.0
                          AAPL    124.169998  130.279999  112117500.0
                          ABBV    160.809998  162.039993    4937500.0
                          ABNB     84.300003   87.385002    3901200.0
                          ABT     108.750000  110.510002    4171900.0
...                                      ...         ...          ...
2023-12-29 00:00:00+00:00 XYL     113.930000  114.089996     698900.0
                          YUM     130.210007  130.410004    1196800.0
                          ZBH     121.239998  121.459999     849600.0
                          ZBRA    272.769989  274.730011     251300.0
                          ZTS     196.250000  196.679993    1007200.0

Price                             Day Percent Change  Previous Close  \
Date                      Ticker
2023-01-03 00:00:00+00:00 A                -0.012635             NaN
                          AAPL             -0.039991             NaN
                          ABBV              0.002098             NaN
                          ABNB             -0.028437             NaN
                          ABT              -0.008416             NaN
...                                              ...             ...
2023-12-29 00:00:00+00:00 XYL               0.002367      114.320000
                          YUM               0.001917      130.520004
                          ZBH               0.001976      121.629997
                          ZBRA             -0.005096      275.350006
                          ZTS               0.003508      197.160004

Price                             Percent Change
Date                      Ticker
2023-01-03 00:00:00+00:00 A                  NaN
                          AAPL               NaN
                          ABBV               NaN
                          ABNB               NaN
                          ABT                NaN
...                                          ...
2023-12-29 00:00:00+00:00 XYL           0.000350
                          YUM           0.001073
                          ZBH           0.000576
                          ZBRA         -0.007336
                          ZTS           0.001065

[123977 rows x 9 columns]

In [4]:
data["Next Day Close"] = data.groupby(level='Ticker')['Close'].shift(-1)
data['Next Day Percent Change'] = (data['Next Day Close'] - data['Close']) / data['Close']
data

Price                             Adj Close       Close        High  \
Date                      Ticker
2023-01-03 00:00:00+00:00 A             NaN  150.039993  153.130005
                          AAPL          NaN  125.070000  130.899994
                          ABBV          NaN  162.380005  163.020004
                          ABNB          NaN   84.900002   88.139999
                          ABT           NaN  109.580002  111.330002
...                                     ...         ...         ...
2023-12-29 00:00:00+00:00 XYL           NaN  114.360001  114.680000
                          YUM           NaN  130.660004  131.250000
                          ZBH           NaN  121.699997  122.400002
                          ZBRA          NaN  273.329987  276.309998
                          ZTS           NaN  197.369995  198.009995

Price                                    Low        Open       Volume  \
Date                      Ticker
2023-01-03 00:00:00+00:00 A       148.470001  151.960007    1414300.0
                          AAPL    124.169998  130.279999  112117500.0
                          ABBV    160.809998  162.039993    4937500.0
                          ABNB     84.300003   87.385002    3901200.0
                          ABT     108.750000  110.510002    4171900.0
...                                      ...         ...          ...
2023-12-29 00:00:00+00:00 XYL     113.930000  114.089996     698900.0
                          YUM     130.210007  130.410004    1196800.0
                          ZBH     121.239998  121.459999     849600.0
                          ZBRA    272.769989  274.730011     251300.0
                          ZTS     196.250000  196.679993    1007200.0

Price                             Day Percent Change  Previous Close  \
Date                      Ticker
2023-01-03 00:00:00+00:00 A                -0.012635             NaN
                          AAPL             -0.039991             NaN
                          ABBV              0.002098             NaN
                          ABNB             -0.028437             NaN
                          ABT              -0.008416             NaN
...                                              ...             ...
2023-12-29 00:00:00+00:00 XYL               0.002367      114.320000
                          YUM               0.001917      130.520004
                          ZBH               0.001976      121.629997
                          ZBRA             -0.005096      275.350006
                          ZTS               0.003508      197.160004

Price                             Percent Change  Next Day Close  \
Date                      Ticker
2023-01-03 00:00:00+00:00 A                  NaN      151.669998
                          AAPL               NaN      126.360001
                          ABBV               NaN      163.690002
                          ABNB               NaN       88.720001
                          ABT                NaN      111.209999
...                                          ...             ...
2023-12-29 00:00:00+00:00 XYL           0.000350             NaN
                          YUM           0.001073             NaN
                          ZBH           0.000576             NaN
                          ZBRA         -0.007336             NaN
                          ZTS           0.001065             NaN

Price                             Next Day Percent Change
Date                      Ticker
2023-01-03 00:00:00+00:00 A                      0.010864
                          AAPL                   0.010314
                          ABBV                   0.008067
                          ABNB                   0.044994
                          ABT                    0.014875
...                                                   ...
2023-12-29 00:00:00+00:00 XYL                         NaN
                          YUM                         NaN
                          ZBH                         NaN
                          ZBRA                        NaN
                          ZTS                         NaN

[123977 rows x 11 columns]

In [ ]:
# Calculate the change between each day's close and the previous day's close for each ticker
data['2 Week Close'] = data.groupby(level='Ticker')['Close'].shift(-10)
data['1 Week Close'] = data.groupby(level="Ticker")['Close'].shift(-5)
data['Percent 2 Week Growth'] = (data['2 Week Close'] - data['Close']) / data['Close']
data['Percent 1 Week Growth'] = (data['1 Week Close'] - data['Close']) / data['Close']
data["Percent 1 to 2 Week Growth"] = (data['2 Week Close'] - data['1 Week Close']) / data['1 Week Close']
data

Price                             Adj Close       Close        High  \
Date                      Ticker
2023-01-03 00:00:00+00:00 A             NaN  150.039993  153.130005
                          AAPL          NaN  125.070000  130.899994
                          ABBV          NaN  162.380005  163.020004
                          ABNB          NaN   84.900002   88.139999
                          ABT           NaN  109.580002  111.330002
...                                     ...         ...         ...
2023-12-29 00:00:00+00:00 XYL           NaN  114.360001  114.680000
                          YUM           NaN  130.660004  131.250000
                          ZBH           NaN  121.699997  122.400002
                          ZBRA          NaN  273.329987  276.309998
                          ZTS           NaN  197.369995  198.009995

Price                                    Low        Open       Volume  \
Date                      Ticker
2023-01-03 00:00:00+00:00 A       148.470001  151.960007    1414300.0
                          AAPL    124.169998  130.279999  112117500.0
                          ABBV    160.809998  162.039993    4937500.0
                          ABNB     84.300003   87.385002    3901200.0
                          ABT     108.750000  110.510002    4171900.0
...                                      ...         ...          ...
2023-12-29 00:00:00+00:00 XYL     113.930000  114.089996     698900.0
                          YUM     130.210007  130.410004    1196800.0
                          ZBH     121.239998  121.459999     849600.0
                          ZBRA    272.769989  274.730011     251300.0
                          ZTS     196.250000  196.679993    1007200.0

Price                             Day Percent Change  Previous Close  \
Date                      Ticker
2023-01-03 00:00:00+00:00 A                -0.012635             NaN
                          AAPL             -0.039991             NaN
                          ABBV              0.002098             NaN
                          ABNB             -0.028437             NaN
                          ABT              -0.008416             NaN
...                                              ...             ...
2023-12-29 00:00:00+00:00 XYL               0.002367      114.320000
                          YUM               0.001917      130.520004
                          ZBH               0.001976      121.629997
                          ZBRA             -0.005096      275.350006
                          ZTS               0.003508      197.160004

Price                             Percent Change  Next Day Close  \
Date                      Ticker
2023-01-03 00:00:00+00:00 A                  NaN      151.669998
                          AAPL               NaN      126.360001
                          ABBV               NaN      163.690002
                          ABNB               NaN       88.720001
                          ABT                NaN      111.209999
...                                          ...             ...
2023-12-29 00:00:00+00:00 XYL           0.000350             NaN
                          YUM           0.001073             NaN
                          ZBH           0.000576             NaN
                          ZBRA         -0.007336             NaN
                          ZTS           0.001065             NaN

Price                             Next Day Percent Change  2 Week Close  \
Date                      Ticker
2023-01-03 00:00:00+00:00 A                      0.010864    154.070007
                          AAPL                   0.010314    135.210007
                          ABBV                   0.008067    149.199997
                          ABNB                   0.044994    101.110001
                          ABT                    0.014875    111.510002
...                                                   ...           ...
2023-12-29 00:00:00+00:00 XYL                         NaN           NaN
                          YUM                         NaN           NaN
                          ZBH                         NaN           NaN
                          ZBRA                        NaN           NaN
                          ZTS                         NaN           NaN

Price                             1 Week Close  Percent 2 Week Growth  \
Date                      Ticker
2023-01-03 00:00:00+00:00 A         155.229996               0.026860
                          AAPL      130.729996               0.081075
                          ABBV      159.639999              -0.081168
                          ABNB       88.540001               0.190930
                          ABT       113.849998               0.017613
...                                        ...                    ...
2023-12-29 00:00:00+00:00 XYL              NaN                    NaN
                          YUM              NaN                    NaN
                          ZBH              NaN                    NaN
                          ZBRA             NaN                    NaN
                          ZTS              NaN                    NaN

Price                             Percent 1 Week Growth  \
Date                      Ticker
2023-01-03 00:00:00+00:00 A                    0.034591
                          AAPL                 0.045255
                          ABBV                -0.016874
                          ABNB                 0.042874
                          ABT                  0.038967
...                                                 ...
2023-12-29 00:00:00+00:00 XYL                       NaN
                          YUM                       NaN
                          ZBH                       NaN
                          ZBRA                      NaN
                          ZTS                       NaN

Price                             Percent 1 to 2 Week Growth
Date                      Ticker
2023-01-03 00:00:00+00:00 A                        -0.007473
                          AAPL                      0.034269
                          ABBV                     -0.065397
                          ABNB                      0.141970
                          ABT                      -0.020553
...                                                      ...
2023-12-29 00:00:00+00:00 XYL                            NaN
                          YUM                            NaN
                          ZBH                            NaN
                          ZBRA                           NaN
                          ZTS                            NaN

[123977 rows x 16 columns]

In [6]:
data["6 Days Prev Close"] = data.groupby(level='Ticker')['Close'].shift(6)
data["6 Days Prev Change"] = (data["Previous Close"] - data["6 Days Prev Close"]) / data["6 Days Prev Close"]
data["1 Month Prev Close"] = data.groupby(level='Ticker')['Close'].shift(24)
data["1 Month Prev Change"] = (data["Previous Close"] - data["1 Month Prev Close"]) / data["1 Month Prev Close"]
data["3 Months Prev Close"] = data.groupby(level='Ticker')['Close'].shift(72)
data["3 Months Prev Change"] = (data["Previous Close"] - data["3 Months Prev Close"]) / data["3 Months Prev Close"]
data["6 Months Prev Close"] = data.groupby(level='Ticker')['Close'].shift(148)
data["6 Months Prev Change"] = (data["Previous Close"] - data["6 Months Prev Close"]) / data["6 Months Prev Close"]

In [7]:
data

Price                             Adj Close       Close        High  \
Date                      Ticker
2023-01-03 00:00:00+00:00 A             NaN  150.039993  153.130005
                          AAPL          NaN  125.070000  130.899994
                          ABBV          NaN  162.380005  163.020004
                          ABNB          NaN   84.900002   88.139999
                          ABT           NaN  109.580002  111.330002
...                                     ...         ...         ...
2023-12-29 00:00:00+00:00 XYL           NaN  114.360001  114.680000
                          YUM           NaN  130.660004  131.250000
                          ZBH           NaN  121.699997  122.400002
                          ZBRA          NaN  273.329987  276.309998
                          ZTS           NaN  197.369995  198.009995

Price                                    Low        Open       Volume  \
Date                      Ticker
2023-01-03 00:00:00+00:00 A       148.470001  151.960007    1414300.0
                          AAPL    124.169998  130.279999  112117500.0
                          ABBV    160.809998  162.039993    4937500.0
                          ABNB     84.300003   87.385002    3901200.0
                          ABT     108.750000  110.510002    4171900.0
...                                      ...         ...          ...
2023-12-29 00:00:00+00:00 XYL     113.930000  114.089996     698900.0
                          YUM     130.210007  130.410004    1196800.0
                          ZBH     121.239998  121.459999     849600.0
                          ZBRA    272.769989  274.730011     251300.0
                          ZTS     196.250000  196.679993    1007200.0

Price                             Day Percent Change  Previous Close  \
Date                      Ticker
2023-01-03 00:00:00+00:00 A                -0.012635             NaN
                          AAPL             -0.039991             NaN
                          ABBV              0.002098             NaN
                          ABNB             -0.028437             NaN
                          ABT              -0.008416             NaN
...                                              ...             ...
2023-12-29 00:00:00+00:00 XYL               0.002367      114.320000
                          YUM               0.001917      130.520004
                          ZBH               0.001976      121.629997
                          ZBRA             -0.005096      275.350006
                          ZTS               0.003508      197.160004

Price                             Percent Change  Next Day Close  ...  \
Date                      Ticker                                  ...
2023-01-03 00:00:00+00:00 A                  NaN      151.669998  ...
                          AAPL               NaN      126.360001  ...
                          ABBV               NaN      163.690002  ...
                          ABNB               NaN       88.720001  ...
                          ABT                NaN      111.209999  ...
...                                          ...             ...  ...
2023-12-29 00:00:00+00:00 XYL           0.000350             NaN  ...
                          YUM           0.001073             NaN  ...
                          ZBH           0.000576             NaN  ...
                          ZBRA         -0.007336             NaN  ...
                          ZTS           0.001065             NaN  ...

Price                             Percent 1 Week Growth  \
Date                      Ticker
2023-01-03 00:00:00+00:00 A                    0.034591
                          AAPL                 0.045255
                          ABBV                -0.016874
                          ABNB                 0.042874
                          ABT                  0.038967
...                                                 ...
2023-12-29 00:00:00+00:00 XYL                       NaN
                          YUM                       NaN
                          ZBH                       NaN
                          ZBRA                      NaN
                          ZTS                       NaN

Price                             Percent 1 to 2 Week Growth  \
Date                      Ticker
2023-01-03 00:00:00+00:00 A                        -0.007473
                          AAPL                      0.034269
                          ABBV                     -0.065397
                          ABNB                      0.141970
                          ABT                      -0.020553
...                                                      ...
2023-12-29 00:00:00+00:00 XYL                            NaN
                          YUM                            NaN
                          ZBH                            NaN
                          ZBRA                           NaN
                          ZTS                            NaN

Price                             6 Days Prev Close  6 Days Prev Change  \
Date                      Ticker
2023-01-03 00:00:00+00:00 A                     NaN                 NaN
                          AAPL                  NaN                 NaN
                          ABBV                  NaN                 NaN
                          ABNB                  NaN                 NaN
                          ABT                   NaN                 NaN
...                                             ...                 ...
2023-12-29 00:00:00+00:00 XYL            109.669998            0.042400
                          YUM            129.039993            0.011469
                          ZBH            120.000000            0.013583
                          ZBRA           261.609985            0.052521
                          ZTS            194.630005            0.012999

Price                             1 Month Prev Close  1 Month Prev Change  \
Date                      Ticker
2023-01-03 00:00:00+00:00 A                      NaN                  NaN
                          AAPL                   NaN                  NaN
                          ABBV                   NaN                  NaN
                          ABNB                   NaN                  NaN
                          ABT                    NaN                  NaN
...                                              ...                  ...
2023-12-29 00:00:00+00:00 XYL             103.260002             0.107108
                          YUM             128.509995             0.015641
                          ZBH             113.430000             0.072291
                          ZBRA            228.919998             0.202822
                          ZTS             180.210007             0.094057

Price                             3 Months Prev Close  3 Months Prev Change  \
Date                      Ticker
2023-01-03 00:00:00+00:00 A                       NaN                   NaN
                          AAPL                    NaN                   NaN
                          ABBV                    NaN                   NaN
                          ABNB                    NaN                   NaN
                          ABT                     NaN                   NaN
...                                               ...                   ...
2023-12-29 00:00:00+00:00 XYL               95.480003              0.197319
                          YUM              127.570000              0.023125
                          ZBH              122.029999             -0.003278
                          ZBRA             253.199997              0.087480
                          ZTS              179.649994              0.097467

Price                             6 Months Prev Close  6 Months Prev Change
Date                      Ticker
2023-01-03 00:00:00+00:00 A                       NaN                   NaN
                          AAPL                    NaN                   NaN
                          ABBV                    NaN                   NaN
                          ABNB                    NaN                   NaN
                          ABT                     NaN                   NaN
...                                               ...                   ...
2023-12-29 00:00:00+00:00 XYL               98.589996              0.159550
                          YUM              127.790001              0.021363
                          ZBH              126.430000             -0.037966
                          ZBRA             267.779999              0.028270
                          ZTS              160.940002              0.225053

[123977 rows x 24 columns]

In [8]:
sorted_data = data.groupby(level=0, group_keys=False).apply(lambda x: x.sort_values('Percent Change', ascending=False))
sorted_data

Price                             Adj Close       Close        High  \
Date                      Ticker
2023-01-03 00:00:00+00:00 A             NaN  150.039993  153.130005
                          AAPL          NaN  125.070000  130.899994
                          ABBV          NaN  162.380005  163.020004
                          ABNB          NaN   84.900002   88.139999
                          ABT           NaN  109.580002  111.330002
...                                     ...         ...         ...
2023-12-29 00:00:00+00:00 BXP           NaN   70.169998   71.730003
                          UBER          NaN   61.570000   63.139999
                          PYPL          NaN   61.410000   63.160000
                          WBD           NaN   11.380000   11.660000
                          ALB           NaN  144.479996  149.029999

Price                                    Low        Open       Volume  \
Date                      Ticker
2023-01-03 00:00:00+00:00 A       148.470001  151.960007    1414300.0
                          AAPL    124.169998  130.279999  112117500.0
                          ABBV    160.809998  162.039993    4937500.0
                          ABNB     84.300003   87.385002    3901200.0
                          ABT     108.750000  110.510002    4171900.0
...                                      ...         ...          ...
2023-12-29 00:00:00+00:00 BXP      70.129997   71.639999     915400.0
                          UBER     61.299999   62.360001   21602500.0
                          PYPL     61.150002   63.000000   16779000.0
                          WBD      11.330000   11.550000   20262200.0
                          ALB     142.149994  149.029999    2834100.0

Price                             Day Percent Change  Previous Close  \
Date                      Ticker
2023-01-03 00:00:00+00:00 A                -0.012635             NaN
                          AAPL             -0.039991             NaN
                          ABBV              0.002098             NaN
                          ABNB             -0.028437             NaN
                          ABT              -0.008416             NaN
...                                              ...             ...
2023-12-29 00:00:00+00:00 BXP              -0.020519       71.949997
                          UBER             -0.012668       63.139999
                          PYPL             -0.025238       63.080002
                          WBD              -0.014719       11.690000
                          ALB              -0.030531      149.429993

Price                             Percent Change  Next Day Close  ...  \
Date                      Ticker                                  ...
2023-01-03 00:00:00+00:00 A                  NaN      151.669998  ...
                          AAPL               NaN      126.360001  ...
                          ABBV               NaN      163.690002  ...
                          ABNB               NaN       88.720001  ...
                          ABT                NaN      111.209999  ...
...                                          ...             ...  ...
2023-12-29 00:00:00+00:00 BXP          -0.024739             NaN  ...
                          UBER         -0.024865             NaN  ...
                          PYPL         -0.026474             NaN  ...
                          WBD          -0.026518             NaN  ...
                          ALB          -0.033126             NaN  ...

Price                             Percent 1 Week Growth  \
Date                      Ticker
2023-01-03 00:00:00+00:00 A                    0.034591
                          AAPL                 0.045255
                          ABBV                -0.016874
                          ABNB                 0.042874
                          ABT                  0.038967
...                                                 ...
2023-12-29 00:00:00+00:00 BXP                       NaN
                          UBER                      NaN
                          PYPL                      NaN
                          WBD                       NaN
                          ALB                       NaN

Price                             Percent 1 to 2 Week Growth  \
Date                      Ticker
2023-01-03 00:00:00+00:00 A                        -0.007473
                          AAPL                      0.034269
                          ABBV                     -0.065397
                          ABNB                      0.141970
                          ABT                      -0.020553
...                                                      ...
2023-12-29 00:00:00+00:00 BXP                            NaN
                          UBER                           NaN
                          PYPL                           NaN
                          WBD                            NaN
                          ALB                            NaN

Price                             6 Days Prev Close  6 Days Prev Change  \
Date                      Ticker
2023-01-03 00:00:00+00:00 A                     NaN                 NaN
                          AAPL                  NaN                 NaN
                          ABBV                  NaN                 NaN
                          ABNB                  NaN                 NaN
                          ABT                   NaN                 NaN
...                                             ...                 ...
2023-12-29 00:00:00+00:00 BXP             70.730003            0.017249
                          UBER            60.680000            0.040541
                          PYPL            61.740002            0.021704
                          WBD             11.660000            0.002573
                          ALB            142.529999            0.048411

Price                             1 Month Prev Close  1 Month Prev Change  \
Date                      Ticker
2023-01-03 00:00:00+00:00 A                      NaN                  NaN
                          AAPL                   NaN                  NaN
                          ABBV                   NaN                  NaN
                          ABNB                   NaN                  NaN
                          ABT                    NaN                  NaN
...                                              ...                  ...
2023-12-29 00:00:00+00:00 BXP              53.709999             0.339602
                          UBER             55.320000             0.141359
                          PYPL             55.759998             0.131277
                          WBD              10.850000             0.077419
                          ALB             128.869995             0.159541

Price                             3 Months Prev Close  3 Months Prev Change  \
Date                      Ticker
2023-01-03 00:00:00+00:00 A                       NaN                   NaN
                          AAPL                    NaN                   NaN
                          ABBV                    NaN                   NaN
                          ABNB                    NaN                   NaN
                          ABT                     NaN                   NaN
...                                               ...                   ...
2023-12-29 00:00:00+00:00 BXP               65.339996              0.101163
                          UBER              46.509998              0.357558
                          PYPL              62.939999              0.002224
                          WBD               11.660000              0.002573
                          ALB              181.619995             -0.177238

Price                             6 Months Prev Close  6 Months Prev Change
Date                      Ticker
2023-01-03 00:00:00+00:00 A                       NaN                   NaN
                          AAPL                    NaN                   NaN
                          ABBV                    NaN                   NaN
                          ABNB                    NaN                   NaN
                          ABT                     NaN                   NaN
...                                               ...                   ...
2023-12-29 00:00:00+00:00 BXP               48.980000              0.468967
                          UBER              37.560001              0.681044
                          PYPL              62.049999              0.016600
                          WBD               11.300000              0.034513
                          ALB              201.860001             -0.259735

[123977 rows x 24 columns]

In [9]:
# Get the top 25 stocks by percent change for each day
top_25_stocks = sorted_data.groupby(level=0, group_keys=False).apply(lambda x: x.nlargest(25, 'Percent Change'))

# Get the bottom 25 stocks by percent change for each day
bottom_25_stocks = sorted_data.groupby(level=0, group_keys=False).apply(lambda x: x.nsmallest(25, 'Percent Change'))

top_25_stocks

Price                             Adj Close       Close        High  \
Date                      Ticker
2023-01-03 00:00:00+00:00 A             NaN  150.039993  153.130005
                          AAPL          NaN  125.070000  130.899994
                          ABBV          NaN  162.380005  163.020004
                          ABNB          NaN   84.900002   88.139999
                          ABT           NaN  109.580002  111.330002
...                                     ...         ...         ...
2023-12-29 00:00:00+00:00 TRV           NaN  190.490005  190.820007
                          TJX           NaN   93.809998   94.290001
                          CHD           NaN   94.559998   94.639999
                          TRGP          NaN   86.870003   86.949997
                          PGR           NaN  159.279999  159.820007

Price                                    Low        Open       Volume  \
Date                      Ticker
2023-01-03 00:00:00+00:00 A       148.470001  151.960007    1414300.0
                          AAPL    124.169998  130.279999  112117500.0
                          ABBV    160.809998  162.039993    4937500.0
                          ABNB     84.300003   87.385002    3901200.0
                          ABT     108.750000  110.510002    4171900.0
...                                      ...         ...          ...
2023-12-29 00:00:00+00:00 TRV     188.809998  189.339996    1048500.0
                          TJX      93.379997   93.589996    5342500.0
                          CHD      93.970001   94.000000    1196600.0
                          TRGP     86.080002   86.470001    1256600.0
                          PGR     158.100006  158.470001    1637500.0

Price                             Day Percent Change  Previous Close  \
Date                      Ticker
2023-01-03 00:00:00+00:00 A                -0.012635             NaN
                          AAPL             -0.039991             NaN
                          ABBV              0.002098             NaN
                          ABNB             -0.028437             NaN
                          ABT              -0.008416             NaN
...                                              ...             ...
2023-12-29 00:00:00+00:00 TRV               0.006074      189.330002
                          TJX               0.002351       93.239998
                          CHD               0.005957       93.989998
                          TRGP              0.004626       86.349998
                          PGR               0.005111      158.339996

Price                             Percent Change  Next Day Close  ...  \
Date                      Ticker                                  ...
2023-01-03 00:00:00+00:00 A                  NaN      151.669998  ...
                          AAPL               NaN      126.360001  ...
                          ABBV               NaN      163.690002  ...
                          ABNB               NaN       88.720001  ...
                          ABT                NaN      111.209999  ...
...                                          ...             ...  ...
2023-12-29 00:00:00+00:00 TRV           0.006127             NaN  ...
                          TJX           0.006113             NaN  ...
                          CHD           0.006064             NaN  ...
                          TRGP          0.006022             NaN  ...
                          PGR           0.005937             NaN  ...

Price                             Percent 1 Week Growth  \
Date                      Ticker
2023-01-03 00:00:00+00:00 A                    0.034591
                          AAPL                 0.045255
                          ABBV                -0.016874
                          ABNB                 0.042874
                          ABT                  0.038967
...                                                 ...
2023-12-29 00:00:00+00:00 TRV                       NaN
                          TJX                       NaN
                          CHD                       NaN
                          TRGP                      NaN
                          PGR                       NaN

Price                             Percent 1 to 2 Week Growth  \
Date                      Ticker
2023-01-03 00:00:00+00:00 A                        -0.007473
                          AAPL                      0.034269
                          ABBV                     -0.065397
                          ABNB                      0.141970
                          ABT                      -0.020553
...                                                      ...
2023-12-29 00:00:00+00:00 TRV                            NaN
                          TJX                            NaN
                          CHD                            NaN
                          TRGP                           NaN
                          PGR                            NaN

Price                             6 Days Prev Close  6 Days Prev Change  \
Date                      Ticker
2023-01-03 00:00:00+00:00 A                     NaN                 NaN
                          AAPL                  NaN                 NaN
                          ABBV                  NaN                 NaN
                          ABNB                  NaN                 NaN
                          ABT                   NaN                 NaN
...                                             ...                 ...
2023-12-29 00:00:00+00:00 TRV            183.839996            0.029863
                          TJX             90.059998            0.035310
                          CHD             91.419998            0.028112
                          TRGP            85.779999            0.006645
                          PGR            155.559998            0.017871

Price                             1 Month Prev Close  1 Month Prev Change  \
Date                      Ticker
2023-01-03 00:00:00+00:00 A                      NaN                  NaN
                          AAPL                   NaN                  NaN
                          ABBV                   NaN                  NaN
                          ABNB                   NaN                  NaN
                          ABT                    NaN                  NaN
...                                              ...                  ...
2023-12-29 00:00:00+00:00 TRV             177.539993             0.066408
                          TJX              89.970001             0.036345
                          CHD              94.830002            -0.008858
                          TRGP             87.839996            -0.016963
                          PGR             163.720001            -0.032861

Price                             3 Months Prev Close  3 Months Prev Change  \
Date                      Ticker
2023-01-03 00:00:00+00:00 A                       NaN                   NaN
                          AAPL                    NaN                   NaN
                          ABBV                    NaN                   NaN
                          ABNB                    NaN                   NaN
                          ABT                     NaN                   NaN
...                                               ...                   ...
2023-12-29 00:00:00+00:00 TRV              166.850006              0.134732
                          TJX               91.940002              0.014140
                          CHD               95.150002             -0.012191
                          TRGP              85.660004              0.008055
                          PGR              140.559998              0.126494

Price                             6 Months Prev Close  6 Months Prev Change
Date                      Ticker
2023-01-03 00:00:00+00:00 A                       NaN                   NaN
                          AAPL                    NaN                   NaN
                          ABBV                    NaN                   NaN
                          ABNB                    NaN                   NaN
                          ABT                     NaN                   NaN
...                                               ...                   ...
2023-12-29 00:00:00+00:00 TRV              173.289993              0.092562
                          TJX               76.760002              0.214695
                          CHD               91.720001              0.024749
                          TRGP              68.489998              0.260768
                          PGR              128.070007              0.236355

[6250 rows x 24 columns]

In [10]:
data['Gainer'] = data.index.isin(top_25_stocks.index)
data['Loser'] = data.index.isin(bottom_25_stocks.index)
data.to_pickle(f'./labelled_market/{chosen_year}.pkl')

In [11]:
top_25_stocks_percentiles_self = [top_25_stocks.groupby(level=0, group_keys=False).apply(lambda x: x.iloc[i-5:i]) for i in range(5, 30, 5)]
bottom_25_stocks_percentiles_self = [bottom_25_stocks.groupby(level=0, group_keys=False).apply(lambda x: x.iloc[i-5:i]) for i in range(5, 30, 5)]

for i, percentile in enumerate(top_25_stocks_percentiles_self):
    percentile.to_pickle(f"./gain_lose_percentiles/{chosen_year}_gainers_{(i+1)*20}.pkl")
    print(percentile.mean()["Percent Change"])

for i, percentile in enumerate(bottom_25_stocks_percentiles_self):
    percentile.to_pickle(f"./gain_lose_percentiles/{chosen_year}_losers_{(i+1)*20}.pkl")
    print(percentile.mean()["Percent Change"])

0.059304266430091866
0.036658356896423286
0.030256762397832815
0.02638219246662476
0.0237537559485627
-0.056677700325578284
-0.03444780098229305
-0.028269188722952438
-0.024690816518279004
-0.022119634490821414

In [12]:
top_25_sorted_f2w = top_25_stocks.groupby(level=0, group_keys=False).apply(lambda x: x.sort_values('Percent 2 Week Growth', ascending=False))
top_25_sorted_f1w = top_25_stocks.groupby(level=0, group_keys=False).apply(lambda x: x.sort_values('Percent 1 Week Growth', ascending=False))
top_25_sorted_6d = top_25_stocks.groupby(level=0, group_keys=False).apply(lambda x: x.sort_values('6 Days Prev Change', ascending=False))
top_25_sorted_1m = top_25_stocks.groupby(level=0, group_keys=False).apply(lambda x: x.sort_values('1 Month Prev Change', ascending=False))
top_25_sorted_3m = top_25_stocks.groupby(level=0, group_keys=False).apply(lambda x: x.sort_values("3 Months Prev Change", ascending=False))
top_25_sorted_6m = top_25_stocks.groupby(level=0, group_keys=False).apply(lambda x: x.sort_values("6 Months Prev Change", ascending=False))

In [13]:
bottom_25_sorted_f2w = bottom_25_stocks.groupby(level=0, group_keys=False).apply(lambda x: x.sort_values('Percent 2 Week Growth', ascending=False))
bottom_25_sorted_f1w = bottom_25_stocks.groupby(level=0, group_keys=False).apply(lambda x: x.sort_values('Percent 1 Week Growth', ascending=False))
bottom_25_sorted_6d = bottom_25_stocks.groupby(level=0, group_keys=False).apply(lambda x: x.sort_values('6 Days Prev Change', ascending=False))
bottom_25_sorted_1m = bottom_25_stocks.groupby(level=0, group_keys=False).apply(lambda x: x.sort_values('1 Month Prev Change', ascending=False))
bottom_25_sorted_3m = bottom_25_stocks.groupby(level=0, group_keys=False).apply(lambda x: x.sort_values('3 Months Prev Change', ascending=False))
bottom_25_sorted_6m = bottom_25_stocks.groupby(level=0, group_keys=False).apply(lambda x: x.sort_values('6 Months Prev Change', ascending=False))

In [14]:
top_25_stocks_percentiles_f2w = [top_25_sorted_f2w.groupby(level=0, group_keys=False).apply(lambda x: x.iloc[i-5:i]) for i in range(5, 30, 5)]
top_25_stocks_percentiles_f1w = [top_25_sorted_f1w.groupby(level=0, group_keys=False).apply(lambda x: x.iloc[i-5:i]) for i in range(5, 30, 5)]
top_25_stocks_percentiles_6d = [top_25_sorted_6d.groupby(level=0, group_keys=False).apply(lambda x: x.iloc[i-5:i]) for i in range(5, 30, 5)]
top_25_stocks_percentiles_1m = [top_25_sorted_1m.groupby(level=0, group_keys=False).apply(lambda x: x.iloc[i-5:i]) for i in range(5, 30, 5)]
top_25_stocks_percentiles_3m = [top_25_sorted_3m.groupby(level=0, group_keys=False).apply(lambda x: x.iloc[i-5:i]) for i in range(5, 30, 5)]
top_25_stocks_percentiles_6m = [top_25_sorted_6m.groupby(level=0, group_keys=False).apply(lambda x: x.iloc[i-5:i]) for i in range(5, 30, 5)]

In [15]:
bottom_25_stocks_percentiles_f2w = [bottom_25_sorted_f2w.groupby(level=0, group_keys=False).apply(lambda x: x.iloc[i-5:i]) for i in range(5, 30, 5)]
bottom_25_stocks_percentiles_f1w = [bottom_25_sorted_f1w.groupby(level=0, group_keys=False).apply(lambda x: x.iloc[i-5:i]) for i in range(5, 30, 5)]
bottom_25_stocks_percentiles_6d = [bottom_25_sorted_6d.groupby(level=0, group_keys=False).apply(lambda x: x.iloc[i-5:i]) for i in range(5, 30, 5)]
bottom_25_stocks_percentiles_1m = [bottom_25_sorted_1m.groupby(level=0, group_keys=False).apply(lambda x: x.iloc[i-5:i]) for i in range(5, 30, 5)]
bottom_25_stocks_percentiles_3m = [bottom_25_sorted_3m.groupby(level=0, group_keys=False).apply(lambda x: x.iloc[i-5:i]) for i in range(5, 30, 5)]
bottom_25_stocks_percentiles_6m = [bottom_25_sorted_6m.groupby(level=0, group_keys=False).apply(lambda x: x.iloc[i-5:i]) for i in range(5, 30, 5)]

In [16]:
for i, percentile in enumerate(top_25_stocks_percentiles_f1w):
    # percentile.to_pickle(f"./f1w_percentiles/{chosen_year}_gainers_{(i+1)*20}.pkl")
    print(percentile.mean()["Percent 1 Week Growth"])

0.06080280843356739
0.021926033712597846
0.003209175918695204
-0.013794306419745208
-0.04650389040298299

In [17]:
for i, percentile in enumerate(bottom_25_stocks_percentiles_f1w):
    # percentile.to_pickle(f"./f1w_percentiles/{chosen_year}_losers_{(i+1)*20}.pkl")
    print(percentile.mean()["Percent 1 Week Growth"])

0.05774140962868955
0.021495089349671377
0.0034868976102596402
-0.01335225395496729
-0.046950830060593474

In [18]:
for i, percentile in enumerate(top_25_stocks_percentiles_6d):
    # percentile.to_pickle(f"./6d_percentiles/{chosen_year}_gainers_{(i+1)*20}.pkl")
    print(percentile.mean()["Percent 2 Week Growth"])

0.009863325082662501
0.01005482523682029
0.011023081270474671
0.006197435068063267
0.010070915252040872

In [19]:
for percentile in top_25_stocks_percentiles_1m:
    print(percentile.mean()["Percent 2 Week Growth"])

0.012168840851390457
0.009157619095150856
0.009180167792117526
0.009468131507140773
0.007234822664261985

In [20]:
for percentile in top_25_stocks_percentiles_3m:
    print(percentile.mean()["Percent 2 Week Growth"])

0.008796663898649875
0.010619405447821135
0.00752068268094568
0.009679537416996025
0.010593292465648888

In [21]:
for percentile in top_25_stocks_percentiles_6m:
    print(percentile.mean()["Percent 2 Week Growth"])

0.01105993283837155
0.011272077509424841
0.0067701421340445244
0.00797060981827743
0.010136819609943254

In [22]:
for i, percentile in enumerate(bottom_25_stocks_percentiles_6d):
    # percentile.to_pickle(f"./6d_percentiles/{chosen_year}_losers_{(i+1)*20}.pkl")
    print(percentile.mean()["Percent 2 Week Growth"])

0.00947849909202749
0.006042042150593021
0.007134839266274193
0.0076458452094225245
0.009704844794498154

In [23]:
for percentile in bottom_25_stocks_percentiles_1m:
    print(percentile.mean()["Percent 2 Week Growth"])

0.010936224625991425
0.005918876193794672
0.009279470188316707
0.005448249749982714
0.008423249754729864

In [24]:
for percentile in bottom_25_stocks_percentiles_3m:
    print(percentile.mean()["Percent 2 Week Growth"])

0.00972207142396009
0.005634006541938668
0.008308288252521969
0.008368709174946401
0.007972995119448252

In [25]:
for percentile in bottom_25_stocks_percentiles_6m:
    print(percentile.mean()["Percent 2 Week Growth"])

0.01025234092794176
0.007838649650601973
0.007260442836516097
0.006981887573255983
0.007672749524499567

In [26]:
top_25_stocks.mean()["Percent 2 Week Growth"]

0.009441916382012321

In [27]:
bottom_25_stocks.mean()["Percent 2 Week Growth"]

0.008001214102563076

In [28]:
data.mean()["Percent 2 Week Growth"]

0.005510769223451545

In [29]:
# bottom_25_stocks.to_pickle(f"./gain_lose/{chosen_year}_top_losers.pkl")
# top_25_stocks.to_pickle(f"./gain_lose/{chosen_year}_top_gainers.pkl")